name: promould
description: ProMould v7.1 Smart Factory
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  path: ^1.9.0
  uuid: ^4.4.0

  # Sharing / utils
  csv: ^6.0.0
  share_plus: ^10.0.2
  flutter_animate: ^4.5.0
  percent_indicator: ^4.2.3
  pdf: ^3.11.1
  fl_chart: ^0.69.0
  logger: ^2.0.2

  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^16.3.3

  # Media / background / charts
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  workmanager: ^0.5.2
  syncfusion_flutter_charts: ^26.1.41
  syncfusion_flutter_gauges: ^26.1.41
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
